version: '3' 
services:
  intellij-docker:
    image: openkbs/intellij-docker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-intellij-docker
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
      - DISPLAY=${DISPLAY:-":0.0"}
    env_file:
      - ./.env
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./IdeaProjects:/home/developer/IdeaProjects
      - ./.IdeaIC2018.1:/home/developer/.IdeaIC2018.1
      - ./data:/home/developer/data
      - ./.java:/home/developer/.java

